# Generated by Django 6.1.1 on 2026-09-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CohortStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('ownership', models.CharField(choices=[('private', 'Private establishments only'), ('government', 'State and local government only'), ('all', 'All establishments')], max_length=10)),
                ('level', models.PositiveSmallIntegerField()),
                ('naics_prefix', models.CharField(max_length=6)),
                ('establishment_count', models.IntegerField()),
                ('p25_trir', models.FloatField()),
                ('median_trir', models.FloatField()),
                ('p75_trir', models.FloatField()),
                ('p90_trir', models.FloatField()),
                ('share_zero', models.FloatField()),
                ('pooled_trir', models.FloatField()),
            ],
            options={
                'db_table': 'cohort_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaicsIndustry',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'NAICS industries',
                'db_table': 'naics_reference',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('establishment_id', models.CharField(max_length=20)),
                ('establishment_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('naics_code', models.CharField(max_length=6)),
                ('naics_code_reported', models.CharField(max_length=6)),
                ('naics_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('industry_description', models.CharField(blank=True, max_length=255)),
                ('establishment_type', models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'State government'), (3, 'Local government')])),
                ('annual_average_employees', models.PositiveIntegerField()),
                ('total_hours_worked', models.BigIntegerField()),
                ('total_deaths', models.PositiveIntegerField()),
                ('total_dafw_cases', models.PositiveIntegerField()),
                ('total_djtr_cases', models.PositiveIntegerField()),
                ('total_other_cases', models.PositiveIntegerField()),
                ('total_dafw_days', models.PositiveIntegerField()),
                ('total_djtr_days', models.PositiveIntegerField()),
                ('recordable_cases', models.PositiveIntegerField()),
                ('trir', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dart', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'establishment_summary',
                'indexes': [models.Index(fields=['year', 'naics_code', 'trir'], name='establishment_cohort_idx', opclasses=['int2_ops', 'varchar_pattern_ops', 'numeric_ops'])],
                'constraints': [models.UniqueConstraint(fields=('establishment_id', 'year'), name='unique_establishment_year')],
            },
        ),
    ]
